# Generated by Django 3.0.3 on 2020-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0002_auto_20200303_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TimeField(null=True),
        ),
    ]
