# Generated by Django 3.0.3 on 2020-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0004_auto_20200303_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
